CREATE TABLE PERSON (
  ID SERIAL NOT NULL,
  USER_NAME VARCHAR(255),
  AGE INT,
  EMAIL VARCHAR(200) UNIQUE ,
 CONSTRAINT  PERSON_EMAIL_CHECK CHECK ( EMAIL LIKE '%@%.COM'),
  CONSTRAINT PERSON_AGE CHECK ( AGE>18 ),
  CONSTRAINT PERSON_PK_RULE PRIMARY KEY (ID)
);