CREATE DATABASE USER1;

CREATE TABLE PERSON (
  ID SERIAL NOT NULL,
  USER_NAME VARCHAR(255),
  AGE INT,
  EMAIL VARCHAR(200) UNIQUE ,
 CONSTRAINT  PERSON_EMAIL_CHECK CHECK ( EMAIL LIKE '%@%.COM'),
  CONSTRAINT PERSON_AGE CHECK ( AGE>18 ),
  CONSTRAINT PERSON_PK_RULE PRIMARY KEY (ID)
);

ALTER TABLE PERSON ADD COLUMN Address varchar(20);
ALTER TABLE PERSON DROP COLUMN Address;
ALTER TABLE PERSON RENAME COLUMN Address TO Location;

ALTER TABLE PERSON ALTER COLUMN location TYPE TEXT;

ALTER TABLE PERSON ALTER COLUMN Location SET NOT NULL ;
ALTER TABLE PERSON ALTER COLUMN Location DROP NOT NULL ;

ALTER TABLE PERSON ADD CONSTRAINT MUST_UNIQUE UNIQUE (Location);


SELECT * FROM PERSON;
DROP DATABASE USER1;

CREATE DATABASE Crypto_Yearly_Market_Analysis;

CREATE TABLE BLOCKCHAIN_ACCESS_TYPE(
    TYPE VARCHAR(200) PRIMARY KEY NOT NULL ,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE BLOCKCHAIN_TOKEN_TYPE(
    TYPE VARCHAR(200) PRIMARY KEY NOT NULL ,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE CONSENSUS_ALGORITHM_TYPE(
    TYPE VARCHAR(200) PRIMARY KEY NOT NULL ,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE BLOCKCHAIN_NETWORK_TYPE(
    TYPE VARCHAR(200) PRIMARY KEY NOT NULL ,
    DESCRIPTION TEXT NOT NULL,
    EXAMPLES TEXT NOT NULL ,
    KEY_FEATURES TEXT NOT NULL
);


CREATE TABLE HASH_ALGO_NAME(
    NAME VARCHAR(200) NOT NULL ,
    CONSENSUS_ALGORITHM_TYPE VARCHAR(200) NOT NULL ,
    DESCRIPTION TEXT NOT NULL ,
    HARDWARE_TYPE TEXT NOT NULL ,
    PROS TEXT NOT NULL ,
    CONS TEXT NOT NULL ,
    ENERGY_EFFICIENCY VARCHAR(50) CHECK ( ENERGY_EFFICIENCY IN ('HIGH','LOW','MODERATE') ) NOT NULL,
    CONSTRAINT HASH_ALGO_NAME_FK_1 FOREIGN KEY (CONSENSUS_ALGORITHM_TYPE) REFERENCES CONSENSUS_ALGORITHM_TYPE(TYPE),
    CONSTRAINT HASH_ALGO_NAME_PK PRIMARY KEY (NAME,CONSENSUS_ALGORITHM_TYPE)
);


ALTER TABLE HASH_ALGO_NAME DROP CONSTRAINT HASH_ALGO_NAME_PK;

ALTER TABLE HASH_ALGO_NAME ADD CONSTRAINT HASH_ALGO_NAME_PK PRIMARY KEY (NAME);

CREATE TABLE CRYPTO(
    NAME VARCHAR(200) NOT NULL ,
    SYMBOL VARCHAR(10),
    MAX_PRICE DECIMAL(65,15) NOT NULL ,
    MAX_PRICE_DATE DATE,
    MIN_PRICE DECIMAL(65,15) NOT NULL ,
    MIN_PRICE_DATE DATE,
    TOTAL_SUPPLY DECIMAL(65,15) NOT NULL ,

    CIRCULATING_SUPPLY DECIMAL(65,15) NOT NULL ,

    BLOCKCHAIN_ACCESS_TYPE VARCHAR(200) NOT NULL ,

    CONSENSUS_ALGORITHM_TYPE VARCHAR(200) NOT NULL ,

    BLOCKCHAIN_NETWORK_TYPE VARCHAR(200) NOT NULL ,

    BLOCKCHAIN_TOKEN_TYPE VARCHAR(200) NOT NULL,

    HASH_ALGO_NAME VARCHAR(200),



    FOUNDER VARCHAR(200) NOT NULL ,
    INITIAL_RELEASE_YEAR CHAR(4) NOT NULL,
    OFFICIAL_WEBSITE VARCHAR(100) NOT NULL ,
    DESCRIPTION_FOR_MAJOR_CHANGES_LIKE_AS_MERGE TEXT NOT NULL ,

    CONSTRAINT CRYPTO_TABLE_PK PRIMARY KEY (SYMBOL),

    CONSTRAINT CRYPTO_TABLE_FK_BLOCKCHAIN_TYPE_FK1 FOREIGN KEY (BLOCKCHAIN_ACCESS_TYPE) REFERENCES BLOCKCHAIN_ACCESS_TYPE(TYPE) ON DELETE CASCADE ,

    CONSTRAINT CRYPTO_TABLE_FK_CONSENSUS_ALGO_FK1 FOREIGN KEY (CONSENSUS_ALGORITHM_TYPE) REFERENCES CONSENSUS_ALGORITHM_TYPE(TYPE) ON DELETE CASCADE ,

    CONSTRAINT CRYPTO_TABLE_FK_BLOCKCHAIN_NETWORK_TYPE_FK1 FOREIGN KEY (BLOCKCHAIN_NETWORK_TYPE) REFERENCES BLOCKCHAIN_NETWORK_TYPE(TYPE) ON DELETE CASCADE ,

    CONSTRAINT CRYPTO_TABLE_FK_BLOCKCHAIN_TOKEN_TYPE_FK1 FOREIGN KEY (BLOCKCHAIN_TOKEN_TYPE) REFERENCES BLOCKCHAIN_TOKEN_TYPE(TYPE) ON DELETE CASCADE ,

    CONSTRAINT CRYPTO_TABLE_FK_HASH_ALGO_NAME_FK1 FOREIGN KEY (HASH_ALGO_NAME) REFERENCES HASH_ALGO_NAME(NAME) ON DELETE CASCADE
);

ALTER TABLE CRYPTO ALTER COLUMN CIRCULATING_SUPPLY DROP NOT NULL ;
ALTER TABLE CRYPTO ALTER COLUMN TOTAL_SUPPLY DROP NOT NULL ;

-- Insert Data Start

-- Insert Data End



